In [8]:
import numpy as np
import pandas as pd
import glob
import random
import os

In [6]:
n_sim_user = 20
n_rec_movie = 10

trainSet = {}
testSet = {}
    
user_sim_matrix = {}
movie_count = 0

In [2]:
# 读取文件
path = r"F:\毕业设计\ItemCF和UserCF协同过滤算法参考代码\MovieRecommendation-master\UserCF" + '\\ratings.csv'
glob.glob(path+'\*.csv')

def load_data_from_csv(path):
    
    # 当用pd.read_csv( )出现 OSError: Initializing from file failed 问题时，一般是因为参数文件名或文件路径包含中文，
    # 所以改为 fr = open(path) data = pd.read_csv(fr)
    # 或者  pd.read_csv(path, engine='python')
    if os.path.exists(path):
        pass
        data = pd.read_csv(path, engine='python',header=0)
#         with open (path) as f:
#             data = pd.read_csv(f)
    return data

data = load_data_from_csv(path)
# data
# np.savez('ratings.npz',data)

userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
5            1       70     3.0   964982400
6            1      101     5.0   964980868
7            1      110     4.0   964982176
8            1      151     5.0   964984041
9            1      157     5.0   964984100
10           1      163     5.0   964983650
11           1      216     5.0   964981208
12           1      223     3.0   964980985
13           1      231     5.0   964981179
14           1      235     4.0   964980908
15           1      260     5.0   964981680
16           1      296     3.0   964982967
17           1      316     3.0   964982310
18           1      333     5.0   964981179
19           1      349     4.0   964982563
20           1      356     4.0   964980962
21           1      362     5.0   964982588
22           1      367     4.0   964981710
23           1      423     3.0   964982363
24           1      441     4.0   964980868
25           1      457     5.0   964981909
26           1      480     4.0   964982346
27           1      500     3.0   964981208
28           1      527     5.0   964984002
29           1      543     4.0   964981179
...        ...      ...     ...         ...
100806     610   150401     3.0  1479543210
100807     610   152077     4.0  1493845817
100808     610   152081     4.0  1493846503
100809     610   152372     3.5  1493848841
100810     610   155064     3.5  1493848456
100811     610   156371     5.0  1479542831
100812     610   156726     4.5  1493848444
100813     610   157296     4.0  1493846563
100814     610   158238     5.0  1479545219
100815     610   158721     3.5  1479542491
100816     610   158872     3.5  1493848024
100817     610   158956     3.0  1493848947
100818     610   159093     3.0  1493847704
100819     610   160080     3.0  1493848031
100820     610   160341     2.5  1479545749
100821     610   160527     4.5  1479544998
100822     610   160571     3.0  1493848537
100823     610   160836     3.0  1493844794
100824     610   161582     4.0  1493847759
100825     610   161634     4.0  1493848362
100826     610   162350     3.5  1493849971
100827     610   163937     3.5  1493848789
100828     610   163981     3.5  1493850155
100829     610   164179     5.0  1493845631
100830     610   166528     4.0  1493879365
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [3]:
# data = np.load('ratings.npz')
# df = data['arr_0']
# # pd.DataFrame(df)
# df[]
(data.loc[0])

pandas.core.series.Series

In [5]:
# read file 
def load_file(filename):
    with open(filename, 'r', encoding='utf-8') as f:
        for i, line in enumerate(f):
            if i == 0:
                # 去掉文件第一行的title
                continue
            yield line.strip('\r\n')
    print('Load %s success!' % filename)

def get_dataset(filename, pivot=0.75):
    trainSet = {}
    testSet = {}
    trainSet_len = 0
    testSet_len = 0
    # 加载文件， 按行读取
    for line in load_file(filename):
        # 读取列属性
        user, movie, rating, timestamp = line.split(',')
        # 数据划分测试集合和数据集合 (0,1) < (0,pivot)
        if random.random() < pivot:
            trainSet.setdefault(user, {})
            trainSet[user][movie] = rating
            trainSet_len += 1
        else:
            testSet.setdefault(user, {})
            testSet[user][movie] = rating
            testSet_len += 1
    print('Split trainingSet and testSet success!')
    print('TrainSet = %s' % trainSet_len)
    print('TestSet = %s' % testSet_len)
    return trainSet, testSet

In [10]:
trainSet, testSet = get_dataset(filename=path)
pd.DataFrame(trainSet)

Load F:\毕业设计\ItemCF和UserCF协同过滤算法参考代码\MovieRecommendation-master\UserCF\ratings.csv success!
Split trainingSet and testSet success!
TrainSet = 75672
TestSet = 25164


1   10  100  101  102  103  104  105  106  107 ...    90   91   92  \
1       4.0  NaN  NaN  NaN  NaN  4.0  NaN  NaN  NaN  4.0 ...   3.0  4.0  NaN   
10      NaN  NaN  NaN  NaN  NaN  NaN  3.0  NaN  NaN  NaN ...   NaN  3.5  NaN   
100     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100044  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100083  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100106  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100159  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100163  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100194  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100226  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
1003    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100302  NaN  NaN  NaN  NaN  NaN  NaN  NaN  3.0  NaN  NaN ...   NaN  NaN  NaN   
100304  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100306  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100326  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100383  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100390  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100397  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
1004    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100487  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100498  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
1005    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100507  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100527  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100553  NaN  NaN  NaN  NaN  NaN  NaN  NaN  4.5  NaN  NaN ...   NaN  NaN  NaN   
100556  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100579  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
1006    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100611  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
1007    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ... ...   ...  ...  ...   
991     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
99106   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
99112   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
99114   NaN  NaN  NaN  NaN  NaN  4.5  NaN  4.0  NaN  NaN ...   NaN  NaN  NaN   
99117   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
99122   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
99145   NaN  NaN  NaN  NaN  NaN  NaN  NaN  4.5  NaN  NaN ...   NaN  NaN  NaN   
99149   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
99191   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
993     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
994     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
99415   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
99437   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
99532   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
99574   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
996     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
99636   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  5.0  NaN ...   NaN  NaN  NaN   
99638   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
99721   Na

In [85]:
path = r"F:\毕业设计\ItemCF和UserCF协同过滤算法参考代码\MovieRecommendation-master\UserCF" 
glob.glob(path+'\*data*')
from contextlib import closing
import shelve

def data_init(path):
    #self.trainSet, self.testSet = load_data.get_dataset(path)
    #  读取测试数据 
    with closing(shelve.open(path,'r')) as shelf:
        trainSet = shelf['train']
        testSet = shelf['test']

    print("train data",len(trainSet),"- test data",len(testSet))
    return trainSet, testSet
trainSet, testSet = data_init(path+'\\time0data')


train data 610 - test data 610


In [118]:
a = pd.Series(trainSet['1'])
b = pd.Series(trainSet['2'])
print(type(a),type(b))


<class 'pandas.core.series.Series'> <class 'pandas.core.series.Series'>


40.0

In [140]:
pd.DataFrame(trainSet)

1   10  100  101  102  103  104  105  106  107 ...    90   91   92  \
1       NaN  NaN  NaN  NaN  NaN  4.0  NaN  NaN  NaN  4.0 ...   NaN  NaN  NaN   
10      NaN  NaN  NaN  NaN  NaN  NaN  3.0  NaN  NaN  NaN ...   NaN  3.5  NaN   
100     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100044  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100068  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100083  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100106  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100159  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100163  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100194  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100226  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100277  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
1003    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100304  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100306  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100326  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100383  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100390  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100397  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
1004    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100487  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100498  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
1005    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100507  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100527  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100553  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100556  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
1006    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
100611  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
1007    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ... ...   ...  ...  ...   
98836   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
98961   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
99      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
990     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
99005   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
99007   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
991     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
99106   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
99112   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
99114   NaN  NaN  NaN  NaN  NaN  NaN  NaN  4.0  NaN  NaN ...   NaN  NaN  NaN   
99117   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
99122   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
99145   NaN  NaN  NaN  NaN  NaN  NaN  NaN  4.5  NaN  NaN ...   NaN  NaN  NaN   
99149   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
993     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
994     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
99415   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
99437   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
99532   Na

In [16]:
def sim_by_series(a,b):
    mul_a_b = a.astype(np.float).mul(b.astype(np.float), fill_value=0).sum()
    a2 = np.sqrt(np.sum(a.astype(np.float).mul(a.astype(np.float),fill_value=0)))
    b2 = np.sqrt(np.sum(b.astype(np.float).mul(b.astype(np.float),fill_value=0)))
    return mul_a_b / (a2 * b2)

# 余弦相似度
def cosine(x,y):
    x = pd.Series(x)
    y = pd.Series(y) 
    xy = x.astype(float).mul(y.astype(float), fill_value=0)
    x = np.linalg.norm(x.values.astype(float),2)
    y = np.linalg.norm(y.values.astype(float),2)
    return xy.sum() / (x*y)


cosine(trainSet.get('3'),trainSet.get('2'))


0.0

In [17]:
# 计算电影之间的相似度, 利用其他算法
def calc_movie_sim_test(trainSet, func):
    movie_sim_matrix = {}

    for user1 in trainSet.keys():
        movie_sim_matrix.setdefault(user1, {})
        for user2 in trainSet.keys():
            if user1 == user2:
                movie_sim_matrix.get(user1).setdefault(user2, 1)
            else:
                movie_sim_matrix.get(user1).setdefault(user2, func(trainSet.get(user1), trainSet.get(user2)))
    # movie{1,2}=sim
    return  movie_sim_matrix


In [18]:
func = cosine
pd.DataFrame(calc_movie_sim_test(trainSet, func))

1        10       100       101       102       103       104  \
1    1.000000  0.011215  0.092030  0.111416  0.140766  0.184045  0.097759   
10   0.011215  1.000000  0.084396  0.023273  0.000000  0.078542  0.127931   
100  0.092030  0.084396  1.000000  0.026550  0.115860  0.086818  0.126396   
101  0.111416  0.023273  0.026550  1.000000  0.000000  0.105035  0.033435   
102  0.140766  0.000000  0.115860  0.000000  1.000000  0.047668  0.077405   
103  0.184045  0.078542  0.086818  0.105035  0.047668  1.000000  0.143869   
104  0.097759  0.127931  0.126396  0.033435  0.077405  0.143869  1.000000   
105  0.077543  0.111242  0.050966  0.041333  0.033423  0.227549  0.107446   
106  0.025495  0.134896  0.000000  0.000000  0.039559  0.164976  0.111810   
107  0.054761  0.000000  0.101362  0.000000  0.180560  0.035492  0.019515   
108  0.052997  0.048467  0.061465  0.032424  0.018434  0.050464  0.047842   
109  0.110792  0.014153  0.149478  0.021770  0.343816  0.081954  0.074257   
11   0.117727  0.039586  0.078888  0.023970  0.220037  0.070520  0.078354   
110  0.161710  0.010573  0.039910  0.090431  0.042655  0.134732  0.067737   
111  0.051835  0.123868  0.062034  0.055230  0.032709  0.170843  0.140739   
112  0.168193  0.112539  0.097039  0.027541  0.183496  0.180870  0.061236   
113  0.051671  0.041368  0.124751  0.000000  0.027043  0.070549  0.087221   
114  0.047629  0.036399  0.037169  0.029999  0.030457  0.089274  0.131562   
115  0.164053  0.022490  0.113861  0.116909  0.141138  0.084919  0.107361   
116  0.128201  0.067107  0.090276  0.042296  0.263016  0.153034  0.111041   
117  0.121349  0.023482  0.137091  0.000000  0.337001  0.086714  0.133209   
118  0.103955  0.007062  0.084022  0.000000  0.044316  0.162447  0.018907   
119  0.052703  0.154134  0.034831  0.036546  0.029968  0.151603  0.064636   
12   0.021438  0.047628  0.130715  0.020461  0.024235  0.020874  0.091976   
120  0.102875  0.000000  0.000000  0.053906  0.038310  0.060878  0.064694   
121  0.075689  0.019022  0.146943  0.000000  0.376658  0.105543  0.082980   
122  0.147474  0.061878  0.089232  0.056252  0.064946  0.243033  0.100278   
123  0.089506  0.043561  0.012998  0.054702  0.028402  0.122744  0.058693   
124  0.156957  0.066723  0.068810  0.107489  0.060358  0.112286  0.047879   
125  0.080690  0.080977  0.038074  0.043606  0.028425  0.135205  0.068250   
..        ...       ...       ...       ...       ...       ...       ...   
72   0.221333  0.044861  0.045071  0.067041  0.210249  0.139682  0.074684   
73   0.036783  0.086730  0.031562  0.019180  0.000000  0.172392  0.114287   
74   0.056665  0.013397  0.005130  0.056786  0.000000  0.151344  0.049021   
75   0.141224  0.036528  0.029974  0.000000  0.047460  0.089110  0.077552   
76   0.172294  0.049822  0.035818  0.089937  0.109986  0.234332  0.082632   
77   0.108764  0.101670  0.000000  0.038754  0.000000  0.135345  0.100365   
78   0.162299  0.020314  0.041797  0.041766  0.138897  0.096348  0.076710   
79   0.173178  0.002087  0.050096  0.027646  0.070403  0.083170  0.010478   
8    0.092118  0.032537  0.139369  0.000000  0.420632  0.089654  0.121958   
80   0.035870  0.057023  0.022783  0.022936  0.011242  0.113563  0.026577   
81   0.103420  0.021466  0.066055  0.000000  0.400776  0.045873  0.056754   
82   0.201022  0.046280  0.092801  0.094542  0.124764  0.120203  0.111473   
83   0.072579  0.145308  0.073771  0.079959  0.034501  0.173663  0.098127   
84   0.147272  0.023507  0.195034  0.011071  0.163911  0.128571  0.094054   
85   0.000000  0.000000  0.000000  0.000000  0.000000  0.016256  0.016230   
86   0.135561  0.093031  0.069719  0.108867  0.118665  0.155674  0.068007   
87   0.015744  0.000000  0.000000  0.000000  0.000000  0.032829  0.095671   
88   0.049849  0.039077  0.030378  0.000000  0.068568  0.213421  0.044740   
89   0.015077  0.042047  0.021214  0.033577  0.002525  0.057155  0.056018   
9    0.054117  0.027571  0.037896  0.000000  0.000000  0.085953  0.013841   
90   0.0

In [13]:
sim_user = np.array(np.zeros((1000,1000)))

for i in trainSet.keys():
    a = pd.Series(trainSet[i])
    for j in trainSet.keys():
#         print(i,j)
        b = pd.Series(trainSet[j])
        sim_user[int(i),int(j)] = sim_by_series(a,b)
        pass
sim_user

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [139]:
pd.DataFrame(sim_user)

0         1         2         3         4         5         6    \
0    0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1    0.0  1.000000  0.039885  0.054755  0.181044  0.105744  0.122378   
2    0.0  0.039885  1.000000  0.000000  0.000000  0.000000  0.035802   
3    0.0  0.054755  0.000000  1.000000  0.002806  0.006323  0.003390   
4    0.0  0.181044  0.000000  0.002806  1.000000  0.118210  0.070770   
5    0.0  0.105744  0.000000  0.006323  0.118210  1.000000  0.207242   
6    0.0  0.122378  0.035802  0.003390  0.070770  0.207242  1.000000   
7    0.0  0.146275  0.040672  0.000000  0.100680  0.065627  0.038531   
8    0.0  0.112734  0.000000  0.006593  0.032284  0.308640  0.264221   
9    0.0  0.056778  0.000000  0.000000  0.015341  0.000000  0.018533   
10   0.0  0.020954  0.025504  0.000000  0.039186  0.033430  0.025843   
11   0.0  0.093819  0.025751  0.000000  0.033914  0.208892  0.197692   
12   0.0  0.010386  0.000000  0.000000  0.016757  0.023849  0.089799   
13   0.0  0.091477  0.057883  0.000000  0.059967  0.000000  0.000000   
14   0.0  0.119870  0.025187  0.003974  0.039313  0.137316  0.288342   
15   0.0  0.143860  0.073510  0.021024  0.072607  0.073932  0.057779   
16   0.0  0.154296  0.020483  0.038786  0.135480  0.066869  0.043968   
17   0.0  0.245277  0.047229  0.012261  0.132425  0.099473  0.088875   
18   0.0  0.176565  0.118705  0.022477  0.107338  0.095996  0.090807   
19   0.0  0.266054  0.000000  0.005237  0.164141  0.066391  0.157559   
20   0.0  0.139297  0.020577  0.003788  0.054800  0.090923  0.065993   
21   0.0  0.106901  0.063028  0.001762  0.047210  0.038653  0.036508   
22   0.0  0.060472  0.099019  0.000527  0.010159  0.000000  0.050573   
23   0.0  0.072406  0.000000  0.000000  0.070053  0.053513  0.018954   
24   0.0  0.110839  0.053864  0.000000  0.023726  0.010115  0.053948   
25   0.0  0.060848  0.166161  0.000000  0.038581  0.000000  0.000000   
26   0.0  0.066892  0.000000  0.000000  0.042821  0.158532  0.158358   
27   0.0  0.190864  0.000000  0.002934  0.111007  0.044145  0.063858   
28   0.0  0.166325  0.058528  0.019115  0.090185  0.056014  0.066820   
29   0.0  0.116487  0.127737  0.000000  0.047517  0.036633  0.042081   
..   ...       ...       ...       ...       ...       ...       ...   
970  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
971  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
972  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
973  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
974  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
975  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
976  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
977  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
978  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
979  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
980  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
981  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
982  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
983  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
984  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
985  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
986  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
987  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
988  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
989  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
990  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
991  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
992  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
993  0.0  0.000000  0.000000  0.000000  0.000

In [123]:
np.sum(mul_a_b) / (a2*b2)

0.039885121789508544

In [20]:
sim_user = np.array(np.zeros((10,10)))
print(sim_user)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [137]:
import sys,time
for i in range(100):
    sys.stdout.write(‘\r%s%%‘%(i+1))
    sys.stdout.flush()
    time.sleep(0.1)

SyntaxError: invalid character in identifier (<ipython-input-137-23f68b6a0d24>, line 3)